# Generated by Django 5.2.7 on 2025-10-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('razon_social', models.CharField(max_length=20)),
                ('cuit', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('calle', models.CharField(max_length=20)),
                ('numero_calle', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
