# Generated by Django 5.2.7 on 2025-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio_adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.TextField(max_length=6000)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
