# Generated by Django 5.2.7 on 2025-10-28 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio_adicional', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_adicional',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
        ),
    ]
