# Generated by Django 5.2.7 on 2025-10-28 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('numero_chasis', models.CharField(max_length=30)),
                ('numero_motor', models.CharField(max_length=30)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendido', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.modelo')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
