# Generated by Django 5.2.7 on 2025-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='image_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
