# Generated by Django 5.2.7 on 2025-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('calle', models.CharField(max_length=30)),
                ('numero_calle', models.IntegerField()),
                ('casa', models.BooleanField()),
                ('edificio', models.BooleanField()),
                ('country_privado', models.BooleanField()),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
